### ISSUE TITLE
Still Image actor being cut off on larger than default board display

### ISSUE THREAD

**Issue by ZommyT** [tajhlande/lmae#11] opened 2024-01-19 17:26 UTC
I am trying to make my own apps built upon your library and I thought I'd start easy. Display a single still image. This has caused me a few issues. 

When displaying the image over a regular 64x32 virtual matrix, the image shows up good with out issue. However, when I display the image (scaled up to fit the larger virtual matrix) on a 128x64 board, the image only shows up in the first 64 columns and 32 rows and then is cut off at that point. Commented below are screen shoots that show what I am describing.

**Comment by ZommyT** [comment] 2024-01-19 17:28
![Still_Image_Good_64x32_board](https://github.com/tajhlande/lmae/assets/152339840/02766f04-f753-4ef4-af1e-d1e356258bad)

**Comment by ZommyT** [comment] 2024-01-19 17:28
![Uploading Still_Image_Issue_128x64_board.PNG…]()

**Comment by tajhlande** [comment] 2024-01-19 23:06
Do you have a test project or couple of files you can share that reproduces the issue?

**Comment by ZommyT** [comment] 2024-01-20 04:27
So I added a png file "gb.png" to the Images directory of you project and this is the code I ran. 

If you run it with the flags "--led-rows=32 --led-cols=64" everything will display fine.

If you run it with "--led-rows=64 --led-cols=128" it will only show up in a quarter of the virtual matrix displayed. See the photos above.

Below is a txt file with the code (obviously the actual code that I run is in a python file but it won't let me upload that type of file here)

[logo_display.txt](https://github.com/tajhlande/lmae/files/13996676/logo_display.txt)

**Comment by tajhlande** [comment] 2024-01-20 23:33
ok have a look at the development branch for this issue.  I found and fixed two problems with your code:

1. the scale factor for 64x32 was the same as the scale factor for 128x64. I doubled it for 128x64, to `0.15`
2. Because you have a non-default display size, it needs to be passed to the `SingleStageRenderLoopApp` instantiation, on line 37

I didn't add the GB logo to the branch, because I'd rather not add copyrighted images here. But I did test it locally, and it worked ok. I see some other minor usability issues with larger matrices, but it did seem to work ok.

**Comment by ZommyT** [comment] 2024-01-22 13:11
Thanks! Where was image_cutoff_test.py added to the branch? I can't find it and want to see how you passed the rows and columns size to SingleStangeRenderLoopApp as an example

**Comment by tajhlande** [comment] 2024-01-22 14:06
the usability issue is with how much screen space the window for the virtual LED display takes.  ideally it would be appropriately responsive to resizing.

**Comment by ZommyT** [comment] 2024-01-22 14:53
Gotcha, thanks. That is not a big deal at all!

Is there an option to turn off the color interpolation between two pixels? For example, in the attached gb logo, is it possible to make the circled pixels just straight green or white, based on what it is mostly filled by in the actual image?
![pixel_interpolation_gb_logo](https://github.com/tajhlande/lmae/assets/152339840/4bdeb0ec-3084-4d18-9470-98a7a05eb92d)

**Comment by tajhlande** [comment] 2024-01-22 14:59
the usability issue is with how much screen space the window for the virtual LED display takes.  ideally it would be appropriately responsive to resizing.

The interpolation you're describing is done by `image.resize()`, not by this library. 
See here: https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize
and maybe try nearest neighbor.  It won't produce ideal results that often, but it also won't do the kind of sampling that interpolates values.  Beyond that, you probably need to hand edit the image to be the way  you want. I have done that with most of the images I am using.

**Comment by tajhlande** [comment] 2024-01-26 21:27
I think all issues are solved, so I'm gonna close this now.  Reopen or open a new issue as needed.

**Closed by tajhlande** 2024-01-26 21:27 UTC
